# Basic dependabot.yml to update npm

version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'master'
    directory: '/'
    schedule:
      interval: 'daily'
      # Check for npm updates at 10am UTC (5am EST)
      time: '10:00'
    reviewers:
      - 'mrz1836'
    assignees:
      - 'mrz1836'
    # Labels must be created first
    labels:
      - 'update'
