# These are supported funding model platforms

github: tonicpow
custom: https://tonicpow.com/?utm_source=github&utm_medium=sponsor-link&utm_campaign=widget-react&utm_term=widget-react&utm_content=widget-react
