# This is a basic workflow to help you get started with Actions
name: widget-ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master and develop branches
  push:
    branches: [master, develop, 'feature/**']
  pull_request:
    branches: [master, develop, 'feature/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build
      - run: npm run test
